[package]
name = "load-balancer-rust"
version = "0.1.0"
authors = ["CryShana <cryshana@cryshana.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.9"
threadpool = "1.8.1"