[package]
name = "load-balancer-rust"
version = "0.1.0"
authors = ["CryShana <cryshana@cryshana.me>"]
edition = "2018"

[dependencies]
ctrlc = "3.1.9"
mio = "0.7.11"

[features]
default = ["mio/os-poll", "mio/net"]
